# Generated by Django 2.1.3 on 2018-11-24 16:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/default.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Admin\\Desktop\\thuchien-python\\pagado\\media'), upload_to='categorys'),
        ),
    ]
