# Generated by Django 2.1.3 on 2018-11-24 22:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('image', models.FileField(default='settings.MEDIA_ROOT/default.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Admin\\Desktop\\backup\\media'), upload_to='category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
