# Generated by Django 2.1.3 on 2018-11-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
